apiVersion: v1
kind: Service
metadata:
  name: posts-service
spec:
  type: NodePort
  selector:
    app: posts
  ports:
    - name: posts
      protocol: TCP
      # this is the post of nodeport service
      port: 4000
      # this is the port of the container
      targetPort: 4000

      # port and nodeport can be different

      # we are sending traffic to port 4000 of the node port service, and the node port service will forward the traffic to port 4000 of the container internally
