apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: query
  template:
    metadata:
      labels:
        app: query
    spec:
      containers:
        - name: query
          image: ayushpatil0810/query:latest
---
apiVersion: v1
kind: Service
metadata:
  name: query-service
spec:
  type: ClusterIP # this is the default type of service, we can also remove this line
  selector:
    app: query
  ports:
    - name: query
      protocol: TCP
      port: 4002
      targetPort: 4002
